name: gTAA AI Validator
description: >
  Valida el cumplimiento arquitectónico gTAA (ISTQB CT-TAE) en proyectos de test automation.
  Detecta 23 tipos de violaciones en proyectos Python, Java, JS/TS y C#.
author: Jose Antonio Membrive Guillen

branding:
  icon: check-circle
  color: blue

inputs:
  project_path:
    description: Ruta al proyecto de test automation a analizar
    required: true
  verbose:
    description: Activar salida detallada con información de violaciones
    required: false
    default: "false"
  ai:
    description: Activar análisis semántico AI (requiere GEMINI_API_KEY como env var)
    required: false
    default: "false"
  provider:
    description: "Proveedor LLM: gemini, mock, o vacío para auto-detección"
    required: false
    default: ""
  config_path:
    description: Ruta al archivo de configuración .gtaa.yaml
    required: false
    default: ""
  python_version:
    description: Versión de Python para el validador
    required: false
    default: "3.12"
  upload_reports:
    description: Subir reportes JSON y HTML como artefactos del workflow
    required: false
    default: "true"

outputs:
  score:
    description: Puntuación de cumplimiento gTAA (0-100)
    value: ${{ steps.analyze.outputs.score }}
  violations:
    description: Número total de violaciones arquitectónicas encontradas
    value: ${{ steps.analyze.outputs.violations }}
  report_json:
    description: Ruta al fichero JSON del reporte generado
    value: ${{ steps.analyze.outputs.report_json }}

runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: ${{ inputs.python_version }}
        cache: pip

    - name: Install gTAA Validator
      shell: bash
      run: pip install --no-cache-dir "${{ github.action_path }}[all]"

    - name: Run gTAA Validator
      id: analyze
      shell: bash
      run: |
        # Construir array de argumentos (sin eval — SEC-01)
        ARGS=()
        ARGS+=("${{ inputs.project_path }}")
        ARGS+=("--json" "gtaa_report.json" "--html" "gtaa_report.html")

        # Opciones condicionales
        if [ "${{ inputs.verbose }}" = "true" ]; then
          ARGS+=("--verbose")
        fi
        if [ "${{ inputs.ai }}" = "true" ]; then
          ARGS+=("--ai")
        fi
        if [ -n "${{ inputs.provider }}" ]; then
          ARGS+=("--provider" "${{ inputs.provider }}")
        fi
        if [ -n "${{ inputs.config_path }}" ]; then
          ARGS+=("--config" "${{ inputs.config_path }}")
        fi

        echo "Executing: gtaa-validator ${ARGS[*]}"

        # Ejecutar directamente sin eval (exit code 1 si hay violaciones criticas)
        set +e
        gtaa-validator "${ARGS[@]}"
        VALIDATOR_EXIT=$?
        set -e

        # Extraer score y violaciones del reporte JSON
        SCORE=$(python3 -c "
        import json
        with open('gtaa_report.json') as f:
            data = json.load(f)
        print(data['summary']['score'])
        ")
        VIOLATIONS=$(python3 -c "
        import json
        with open('gtaa_report.json') as f:
            data = json.load(f)
        print(data['summary']['total_violations'])
        ")

        # Establecer outputs
        echo "score=$SCORE" >> "$GITHUB_OUTPUT"
        echo "violations=$VIOLATIONS" >> "$GITHUB_OUTPUT"
        echo "report_json=gtaa_report.json" >> "$GITHUB_OUTPUT"

        # Resumen en el log de GitHub Actions
        echo "::notice::gTAA Compliance Score: ${SCORE}/100 | Violations: ${VIOLATIONS}"

        exit $VALIDATOR_EXIT

    - name: Upload reports as artifacts
      if: inputs.upload_reports == 'true' && always()
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: gtaa-validator-reports
        path: |
          gtaa_report.json
          gtaa_report.html
        retention-days: 30
